import JudgeSignup from "./signup/judgeSignUp";
import ClientSignup from "./signup/clientSignUp";
import LawyerSignup from "./signup/lawyerSignUp";
import Login from "./login/login";
import Notification from "./notification/notification";
import NfCalendar from "./calender/calender";
import ProfilePage from "./profile/profile";
import LawyerDocument from "./documents/lawyerDocument";
import Collaborate from "./collaborate/collaborate";
export {JudgeSignup,ClientSignup,LawyerSignup,Login,Notification,NfCalendar,ProfilePage,LawyerDocument,Collaborate};